### PR TITLE
Updated recipes to reflect version downloading (Office 2019)

### LINKED ISSUE #5: Office2016 SKUless
While this downloads the latest version (as of now 16.22.*) it still uses the 16.17 version number which causes munki to not push the update.

### PR DESCRIPTION
**Pull request by WardsParadox**
Fixes #5 

Updates all identifiers to 2019 instead of 2016
Changes description to 2019
Puts the latest 2019 suite version instead of the old 2016 version.

### CODE REVIEW

**Comment by arubdesu** [comment]
Here's the only thing - I'm almost certainly not going to test this anytime soon, so while I'm merging this and will take responsibility for feedback/complaints, I'm doing it kindof blind because it's not a process I need to support currently. Pardon it even took this long to review/merge!

**Comment by arubdesu** [comment]
Er, actually the changed processor having a new required variable is applied inconsistently, can you please add a commit to make it the o365 versions across the board in the recipes? (e.g. install and munki variants are using vl2019 https://github.com/arubdesu/office-recipes/blob/a58dabe6be2cd822003c70c2884a9d793f07fe12/Office2019Suite-SKUless/Office2019SuiteSKUless.install.recipe#L29

**Comment by WardsParadox** [comment]
Whoops! I'll get that corrected. I think @apizz on Slack is also testing this so I'll get some feedback from them on it as well.

**Comment by arubdesu** [comment]
Looks good, FYI I'm squashing the commits down for the merge. As I hinted at, I'm fine with people complaining if they expect volume licensed as the default, with the way Adobe and other vendors I think people accept this as the state that will be more prevalent anyway.

**Pull request merged**
